### ISSUE TITLE
"RandonPrimaryWeaponsToGiveOnSpawn"

### ISSUE THREAD

**Issue by IcySteam** [zWolfi/INS_Sandstorm#2]
not sure if it's supposed to be "RandomPrimaryWeaponsToGiveOnSpawn" instead

**Comment by zDestinate** [comment]
Its actually "RandonPrimaryWeaponsToGiveOnSpawn". I did not make a typo there. It actually NWI typo so it becomes a real thing.

Rcon it with gamemodeproperty then you will see. It will only work if you are running CheckpointHardcore gamemode.
