### ISSUE TITLE
about bUsePlayerStartScoring and MaxPlayerStartsToScore

### ISSUE THREAD

**Issue by heromanofe** [zWolfi/INS_Sandstorm#5]
So, 
bUsePlayerStartScoring=False - (Toggle to use StartsScore or to just use randomized spawn)
MaxPlayerStartsToScore=20 - Selected between 20 different scored spawns to choose a random one (TDM/Domination)

**Comment by zDestinate** [comment]
Those 2 exist but I'm not sure what it does because I can't get it working. You got it working?

**Comment by heromanofe** [comment]
no, asked one dev. basically bUsesAdvancedSpawning = False (bool, No Flags), and those 2 are things for their re spawn system. you could try using those 2 in DM\DOMINATION gamemodes and check if it is true

**Comment by zDestinate** [comment]
Someone has to test this out for us. My schedule is pack.
