### ISSUE TITLE
Could you help me in two situations ? Thanks

### ISSUE THREAD

**Issue by uandsonglauber** [zWolfi/INS_Sandstorm#6]
Hello, how are you ?

I have edited this material several times.
hahahahaha

So! I had this problem.
Each turn of the game counts 2 rounds.

Situation 1:

https://www.youtube.com/watch?v=1_1Z3cEe1Y8&feature=youtu.be

I reinstalled everything and it worked.
I don't know what I did.
Apparently resolved.

Situation 2

https://prnt.sc/rx1da0

Could you explain me.
About XP
About Checkpoint Hardcore
How to put ?
And because the server has molecule DNA, another is a notpad.

These differences make people look for better configured servers.

Hugs.
Waiting.
Thanks;

**Comment by uandsonglauber** [comment]
I forgot about this situation.
Can you help me.
How to leave my server with XP?
How to really adjust to hardcore checkpoint mode?

https://prnt.sc/rwrplf

I see that there is a configuration pattern that people play the most. My server is new and people are also not getting into the configuration, maybe. Thanks!

**Comment by zDestinate** [comment]
For the first problem, I can only think that you messed with the time. It one of those time config causing it.

Base on your screenshot. Those are server info. The XP icon is mean the player playing in that server will get exp and level up. You have to enable the server stats in your server for people to gain exp.

The Checkpoint Hardcore is a game mode where you can set in your map cycle and in your startup parameter. Checkpoint hardcore is different than the normal hardcore. Like movement speed is slow and some HUD is removed.

If you take a look at my map cycle you can see the mode in there. Just put CheckpointHardcore in the mode.
https://github.com/zWolfi/INS_Sandstorm/blob/master/Insurgency/Config/Server/MapCycle.txt

For the DNA one, that's mean the server is using at least a mutator in there.

You should take a look at the official admin guide for more information:
https://insurgencysandstorm.mod.io/guides/server-admin-guide

**Comment by uandsonglauber** [comment]
Thanks!
Could you tell me how I enable XP?

I'm still setting up.

**Comment by daddymacdave** [comment]
login to your steam account and you'll need to general a GLST - 1 for each server
https://steamcommunity.com/dev/managegameservers

**Comment by uandsonglauber** [comment]
Thanks!
Working everything.

Thanks : )
