### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by BioRage** [zWolfi/INS_Sandstorm#7]
Hi there,

I followed the paths and replace everything; but can't seem to start the .batch properly, it stops after this? 

Any suggestions?

![Untitled](https://user-images.githubusercontent.com/833613/85214928-be957980-b33f-11ea-8415-843e41944f52.png)

---
Engine.ini & Game.ini

\sandstorm_server\Insurgency\Saved\Config\WindowsServer

---
MapCycle.txt
\sandstorm_server\Insurgency\Config\Server

---

start.bat

https://pastebin.com/PuD5UuxS

**Comment by zDestinate** [comment]
It supposes to stop there. That's how the server load up until someone joins the server. Otherwise, it will keep hibernating.
