### ISSUE TITLE
Can I repack PUBG Mobile base.pak

### ISSUE THREAD

**Issue by hannan7ahmed** [zWolfi/INS_Sandstorm#8]
Can I repack Base.pak folder into base.pak file?
I'm trying but the size gets little bit smaller with unrealpak.exe.
Can this be used to pack pubg mobile files?
I want to try it on mobile base.pak
I have extracted base.pak successful but I can't repack it to .pak and I tried to repack it with unrealpak.exe but game doesn't load and show this message "Failed to open descriptor file'../../../ShadowTrackerExtra/ShadowTrackerExtra.uproject' "

**Comment by zDestinate** [comment]
I do not know.
I don't play that game. The unrealpak here is most likely for sandstorm.
